<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $user_id
 * @property string $title
 * @property clob $body
 * @property string $image
 * @property Category $Category
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getCategoryId()  Returns the current record's "category_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method clob        getBody()        Returns the current record's "body" value
 * @method string      getImage()       Returns the current record's "image" value
 * @method Category    getCategory()    Returns the current record's "Category" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Post        setCategoryId()  Sets the current record's "category_id" value
 * @method Post        setUserId()      Sets the current record's "user_id" value
 * @method Post        setTitle()       Sets the current record's "title" value
 * @method Post        setBody()        Sets the current record's "body" value
 * @method Post        setImage()       Sets the current record's "image" value
 * @method Post        setCategory()    Sets the current record's "Category" value
 * @method Post        setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    My Project
 * @subpackage model
 * @author     Gabriel Dornescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('form', true);
        $this->option('filter', true);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}