<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    My Project
 * @subpackage model
 * @author     Gabriel Dornescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
	public static function getArticles($max = 3)
	{

		/** @var Post[] $q */
		try {
			$q = Doctrine_Query::create()->from('Post a')->orderBy('a.created_at DESC')->limit($max)->execute();

		} catch (Doctrine_Query_Exception $e)
		{
			echo "ERROR: " . $e->getMessage();
		}
		return $q;
	}
}