<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/12/21 07:28:12
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
