<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/12/21 12:37:26
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
