<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/12/21 07:29:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=myproject',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
