<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/12/21 07:29:20
$this->security = array (
  'new' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
